CREATE TABLE RESERVATIONS(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    RESERVATION TIMESTAMP NOT NULL,
    DESCRIPTION TEXT,
    AMOUNT INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY(ID)
) ENGINE=MYISAM COLLATE LATIN1_GENERAL_CS;
